version: '3.9'

services:
  hospitalmanagement.web.api:
    image: ${DOCKER_REGISTRY-}hospitalmanagementwebapi
    build:
      context: .
      dockerfile: HospitalManagement.Web.Api/Dockerfile

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: hospital_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "student@hospital.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminP@ssw0rd!"
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SETUP_EMAIL: "student@hospital.com"
      PGADMIN_SETUP_PASSWORD: "pgadminP@ssw0rd!"
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin 
      - ./servers.json:/pgadmin4/servers.json

volumes:
  local_pgdata:
  pgadmin-data:
