//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HospitalManagement.Services.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen detaylarla randevu bulunamadı..
        /// </summary>
        internal static string Appointment_Validation_AppointmentNotFound {
            get {
                return ResourceManager.GetString("Appointment.Validation.AppointmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih zorunludur..
        /// </summary>
        internal static string Appointment_Validation_DateIsRequired {
            get {
                return ResourceManager.GetString("Appointment.Validation.DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor bulunamadı..
        /// </summary>
        internal static string Appointment_Validation_DoctorNotFound {
            get {
                return ResourceManager.GetString("Appointment.Validation.DoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu süresi zorunludur..
        /// </summary>
        internal static string Appointment_Validation_DurationIsRequired {
            get {
                return ResourceManager.GetString("Appointment.Validation.DurationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta bulunamadı..
        /// </summary>
        internal static string Appointment_Validation_PatientNotFound {
            get {
                return ResourceManager.GetString("Appointment.Validation.PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu nedeni zorunludur..
        /// </summary>
        internal static string Appointment_Validation_ReasonIsRequired {
            get {
                return ResourceManager.GetString("Appointment.Validation.ReasonIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanı bulunamadı..
        /// </summary>
        internal static string Diagnosis_Validation_DiagnosisNotFound {
            get {
                return ResourceManager.GetString("Diagnosis.Validation.DiagnosisNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanı adı zorunludur..
        /// </summary>
        internal static string Diagnosis_Validation_NameIsRequired {
            get {
                return ResourceManager.GetString("Diagnosis.Validation.NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad 100 karakterden fazla olamaz..
        /// </summary>
        internal static string Diagnosis_Validation_NameLength {
            get {
                return ResourceManager.GetString("Diagnosis.Validation.NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktorun müsaitliği zorunludur..
        /// </summary>
        internal static string Doctor_Validation_AvailabilityIsRequired {
            get {
                return ResourceManager.GetString("Doctor.Validation.AvailabilityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor bulunamadı..
        /// </summary>
        internal static string Doctor_Validation_DoctorNotFound {
            get {
                return ResourceManager.GetString("Doctor.Validation.DoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktorun adı zorunludur..
        /// </summary>
        internal static string Doctor_Validation_FistNameIsRequired {
            get {
                return ResourceManager.GetString("Doctor.Validation.FistNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktorun soyadı zorunludur..
        /// </summary>
        internal static string Doctor_Validation_LastNameIsRequired {
            get {
                return ResourceManager.GetString("Doctor.Validation.LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlık alanı zorunludur..
        /// </summary>
        internal static string Doctor_Validation_SpecializationIsRequired {
            get {
                return ResourceManager.GetString("Doctor.Validation.SpecializationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta adresi girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_AddressIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.AddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın kan grubu girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_BloodTypeIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.BloodTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın doğum tarihi girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_DateOfBirthIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.DateOfBirthIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın e-posta adresi girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_EmailAddressIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.EmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın adı girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_FirstNameIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın soyadı girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_LastNameIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta bulunamadı..
        /// </summary>
        internal static string Patient_Validation_PatientNotFound {
            get {
                return ResourceManager.GetString("Patient.Validation.PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastanın telefon numarası girilmesi zorunludur..
        /// </summary>
        internal static string Patient_Validation_PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("Patient.Validation.PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol tanımı girilmesi zorunludur..
        /// </summary>
        internal static string Role_Validation_DescriptionIsRequired {
            get {
                return ResourceManager.GetString("Role.Validation.DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol adı girilmesi zorunludur..
        /// </summary>
        internal static string Role_Validation_NameIsRequired {
            get {
                return ResourceManager.GetString("Role.Validation.NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol bulunamadı..
        /// </summary>
        internal static string Role_Validation_RoleNotFound {
            get {
                return ResourceManager.GetString("Role.Validation.RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semptom adı girilmesi zorunludur..
        /// </summary>
        internal static string Symptom_Validation_NameIsRequired {
            get {
                return ResourceManager.GetString("Symptom.Validation.NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semptom bulunamadı..
        /// </summary>
        internal static string Symptom_Validation_SymptomNotFound {
            get {
                return ResourceManager.GetString("Symptom.Validation.SymptomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Validation_PasswordIsRequired {
            get {
                return ResourceManager.GetString("User.Validation.PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Validation_RoleIdIsRequired {
            get {
                return ResourceManager.GetString("User.Validation.RoleIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Validation_UserIdIsRequired {
            get {
                return ResourceManager.GetString("User.Validation.UserIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Validation_UserNameIsRequired {
            get {
                return ResourceManager.GetString("User.Validation.UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Validation_UserNotFound {
            get {
                return ResourceManager.GetString("User.Validation.UserNotFound", resourceCulture);
            }
        }
    }
}
